export const productsData = [
    {
        id: 1,
        name: 'Laptop Acer Aspire 7',
        price: 30999,
        image: 'https://content1.rozetka.com.ua/goods/images/big/362592316.jpg',
        brand: 'Acer',
        seller: 'Rozetka',
        link: 'https://rozetka.com.ua/ua/acer-nhqn4eu001/p391395969/',
    },
    {
        id: 2,
        name: 'Ноутбук Lenovo IdeaPad Slim 3',
        price: 21999,
        image: 'https://content.rozetka.com.ua/goods/images/big/353726664.jpg',
        brand: 'Lenovo',
        seller: 'Rozetka',
        link: 'https://rozetka.com.ua/ua/lenovo-82xq009hra/p389016597/',
    },
    {
        id: 3,
        name: 'Ноутбук ASUS Vivobook 15',
        price: 17499,
        image: 'https://content.rozetka.com.ua/goods/images/big/334343847.jpg',
        brand: 'Lenovo',
        seller: 'Rozetka',
        link: 'https://rozetka.com.ua/ua/asus-90nb0ty6-m040w0/p379852182/',
    },
    {
        id: 4,
        name: 'Ноутбук HP Pavilion 15-eh1106ua',
        price: 22999,
        image: 'https://content1.rozetka.com.ua/goods/images/big/207625738.jpg',
        brand: 'HP',
        seller: 'ALLO',
        link: 'https://rozetka.com.ua/ua/hp-4a7n2ea/p314213398/',
    },
    {
        id: 5,
        name: 'Ноутбук Acer Aspire 7 A715-43G-R92H',
        price: 32999,
        image: 'https://content1.rozetka.com.ua/goods/images/big/354763646.jpg',
        brand: 'Acer',
        seller: 'ALLO',
        link: 'https://rozetka.com.ua/ua/acer-nhqhheu00g/p389616942/',
    },
    {
        id: 6,
        name: 'Ноутбук Lenovo IdeaPad Slim 5',
        price: 26999,
        image: 'https://content.rozetka.com.ua/goods/images/big/334492324.jpg',
        brand: 'Lenovo',
        seller: 'ALLO',
        link: 'https://rozetka.com.ua/ua/acer-nhqhheu00g/p389616942/',
    },
    {
        id: 7,
        name: 'Ноутбук Pixus Vix Lite',
        price: 23999,
        image: 'https://content2.rozetka.com.ua/goods/images/big/352760176.jpg',
        brand: 'Pixus',
        seller: 'ALLO',
        link: 'https://rozetka.com.ua/ua/pixus-vix-lite-windows-11-home-silver-black/p388474827/',
    },
]
